services:
  - type: web
    name: calmconnect
    env: python
    plan: standard
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput --clear
    startCommand: >
      python manage.py migrate --noinput &&
      daphne -b 0.0.0.0 -p $PORT calmconnect_backend.asgi:application
    healthCheckPath: /
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ALLOWED_HOSTS
        value: "*"

  - type: pserv
    name: calmconnect-db
    ipAllowList: []
    plan: standard
    postgresVersion: 15
    envVars:
      - key: POSTGRES_DB
        value: calmconnect
      - key: POSTGRES_USER
        generateValue: true
      - key: POSTGRES_PASSWORD
        generateValue: true
